snoke_websocket:
  context: []
# configure following lines to use TLS
#  context:
#    tls:
#      local_cert: 'path/to/server.pem'
#      local_pk: 'path/to/private.key'
#      allow_self_signed: true
#      verify_peer: false
